import type { Metadata } from "next";
import { Arvo} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Providers from "./providers/providers";

const arvo = Arvo({
  subsets: ["latin"],
  weight: ["400", "700"]
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arvo.className} antialiased`}
      >
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>

      </body>
    </html>
  );
}
